import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ProjectLinkAddedPayload as ContractsProjectLinkAddedPayloadSchema,
  ProjectLinkRemovedPayload as ContractsProjectLinkRemovedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  IssueCreatedPayload as ContractsIssueCreatedPayloadSchema,
  IssueUpdatedPayload as ContractsIssueUpdatedPayloadSchema,
  IssueStatusSetPayload as ContractsIssueStatusSetPayloadSchema,
  IssueDeletedPayload as ContractsIssueDeletedPayloadSchema,
  IssueStartedPayload as ContractsIssueStartedPayloadSchema,
  IssueStartFailedPayload as ContractsIssueStartFailedPayloadSchema,
  IssuePullRequestLinkedPayload as ContractsIssuePullRequestLinkedPayloadSchema,
  IssueAttentionFlaggedPayload as ContractsIssueAttentionFlaggedPayloadSchema,
  IssueAttentionClearedPayload as ContractsIssueAttentionClearedPayloadSchema,
  IssueReviewStartedPayload as ContractsIssueReviewStartedPayloadSchema,
  IssueReviewRecordedPayload as ContractsIssueReviewRecordedPayloadSchema,
  IssueReviewResetPayload as ContractsIssueReviewResetPayloadSchema,
  ProjectAutonomousEnabledPayload as ContractsProjectAutonomousEnabledPayloadSchema,
  ProjectAutonomousDisabledPayload as ContractsProjectAutonomousDisabledPayloadSchema,
  ProjectAutonomousScheduleSetPayload as ContractsProjectAutonomousScheduleSetPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const ProjectLinkAddedPayload = ContractsProjectLinkAddedPayloadSchema;
export const ProjectLinkRemovedPayload = ContractsProjectLinkRemovedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const IssueCreatedPayload = ContractsIssueCreatedPayloadSchema;
export const IssueUpdatedPayload = ContractsIssueUpdatedPayloadSchema;
export const IssueStatusSetPayload = ContractsIssueStatusSetPayloadSchema;
export const IssueDeletedPayload = ContractsIssueDeletedPayloadSchema;
export const IssueStartedPayload = ContractsIssueStartedPayloadSchema;
export const IssueStartFailedPayload = ContractsIssueStartFailedPayloadSchema;
export const IssuePullRequestLinkedPayload = ContractsIssuePullRequestLinkedPayloadSchema;
export const IssueAttentionFlaggedPayload = ContractsIssueAttentionFlaggedPayloadSchema;
export const IssueAttentionClearedPayload = ContractsIssueAttentionClearedPayloadSchema;
export const IssueReviewStartedPayload = ContractsIssueReviewStartedPayloadSchema;
export const IssueReviewRecordedPayload = ContractsIssueReviewRecordedPayloadSchema;
export const IssueReviewResetPayload = ContractsIssueReviewResetPayloadSchema;
export const ProjectAutonomousEnabledPayload = ContractsProjectAutonomousEnabledPayloadSchema;
export const ProjectAutonomousDisabledPayload = ContractsProjectAutonomousDisabledPayloadSchema;
export const ProjectAutonomousScheduleSetPayload =
  ContractsProjectAutonomousScheduleSetPayloadSchema;
